In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\babus\Data_Spark\Data Analytics\Data Collection\animal_category.csv")
df_1 = df.copy()
df_2 = df.copy()
df_3 = df.copy()
df_4 = df.copy()

In [3]:
df.head()

   Index Animals  Gender Homly Types
0      1     Cat    Male   Yes     A
1      2     Dog    Male   Yes     B
2      3   Mouse    Male   Yes     C
3      4   Mouse    Male   Yes     C
4      5     Dog  Female   Yes     A

In [4]:
df.drop(columns=['Index'],inplace=True)

In [5]:
df.head()

  Animals  Gender Homly Types
0     Cat    Male   Yes     A
1     Dog    Male   Yes     B
2   Mouse    Male   Yes     C
3   Mouse    Male   Yes     C
4     Dog  Female   Yes     A

In [6]:
df.shape

(30, 4)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Animals  30 non-null     object
 1   Gender   30 non-null     object
 2   Homly    30 non-null     object
 3   Types    30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [8]:
df.size

120

# converting into Numerical

# GetDummy

In [9]:
df.columns

Index(['Animals', 'Gender', 'Homly', 'Types'], dtype='object')

In [10]:
df['Animals'].value_counts()

Animals
Lion     12
Cat       6
Dog       5
Goat      5
Mouse     2
Name: count, dtype: int64

In [11]:
df.nunique()

Animals    5
Gender     2
Homly      2
Types      5
dtype: int64

In [12]:
df['Animals'].unique()

array(['Cat', 'Dog', 'Mouse', 'Lion', 'Goat'], dtype=object)

In [13]:
data = pd.get_dummies(df,drop_first=True).astype('int')
data.head()

,Animals_Dog,Animals_Goat,Animals_Lion,Animals_Mouse,Gender_Male,Homly_Yes,Types_B,Types_C,Types_D,Types_E
0,0,0,0,0,1,1,0,0,0,0
1,1,0,0,0,1,1,1,0,0,0
2,0,0,0,1,1,1,0,1,0,0
3,0,0,0,1,1,1,0,1,0,0
4,1,0,0,0,0,1,0,0,0,0

 # OneHotEncoder (sklearn)

In [14]:
df_1.head()

   Index Animals  Gender Homly Types
0      1     Cat    Male   Yes     A
1      2     Dog    Male   Yes     B
2      3   Mouse    Male   Yes     C
3      4   Mouse    Male   Yes     C
4      5     Dog  Female   Yes     A

In [15]:
df_1.drop(columns=['Index'],inplace=True)

In [16]:
df_1.head()

  Animals  Gender Homly Types
0     Cat    Male   Yes     A
1     Dog    Male   Yes     B
2   Mouse    Male   Yes     C
3   Mouse    Male   Yes     C
4     Dog  Female   Yes     A

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [41]:
enc = OneHotEncoder(drop='first')
arr_enc = enc.fit_transform(df_1).toarray()
arr_enc

array([[0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0.]])

In [42]:
enc_1 = OneHotEncoder()
arr_enc = enc_1.fit_transform(df_1[['Animals']]).toarray()
x = pd.DataFrame(arr_enc,columns=['A','B','C','D','E'])
x.head()

     A    B    C    D    E
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  1.0
3  0.0  0.0  0.0  0.0  1.0
4  0.0  1.0  0.0  0.0  0.0

In [44]:
col_names = enc.get_feature_names_out(['Animals','Gender','Homly','Types'])
col_names

array(['Animals_Dog', 'Animals_Goat', 'Animals_Lion', 'Animals_Mouse',
       'Gender_Male', 'Homly_Yes', 'Types_B', 'Types_C', 'Types_D',
       'Types_E'], dtype=object)

# LABEL ENCODING

In [23]:
df_2.head()

   Index Animals  Gender Homly Types
0      1     Cat    Male   Yes     A
1      2     Dog    Male   Yes     B
2      3   Mouse    Male   Yes     C
3      4   Mouse    Male   Yes     C
4      5     Dog  Female   Yes     A

In [24]:
df_2.drop(columns=['Index'],inplace=True)

In [25]:
df_2.columns

Index(['Animals', 'Gender', 'Homly', 'Types'], dtype='object')

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
lbc = LabelEncoder()

In [28]:
df_2['Animals'] = lbc.fit_transform(df_2['Animals'])

In [29]:
for col in df_2.columns:
    lbc = LabelEncoder()
    df_2[col] = lbc.fit_transform(df_2[col])

In [30]:
df_2.head()

   Animals  Gender  Homly  Types
0        0       1      1      0
1        1       1      1      1
2        4       1      1      2
3        4       1      1      2
4        1       0      1      0

In [31]:
df_2["Animals"] = lbc.inverse_transform(df_2['Animals'])

In [32]:
df_2.head()

  Animals  Gender  Homly  Types
0       A       1      1      0
1       B       1      1      1
2       E       1      1      2
3       E       1      1      2
4       B       0      1      0

In [33]:
mapping = list(
    zip(
        lbc.classes_,lbc.transform(lbc.classes_)
    )
)
mapping

[('A', np.int64(0)),
 ('B', np.int64(1)),
 ('C', np.int64(2)),
 ('D', np.int64(3)),
 ('E', np.int64(4))]

In [34]:
df_2.head()

  Animals  Gender  Homly  Types
0       A       1      1      0
1       B       1      1      1
2       E       1      1      2
3       E       1      1      2
4       B       0      1      0

# MAPPING

In [35]:
df_3.head()

   Index Animals  Gender Homly Types
0      1     Cat    Male   Yes     A
1      2     Dog    Male   Yes     B
2      3   Mouse    Male   Yes     C
3      4   Mouse    Male   Yes     C
4      5     Dog  Female   Yes     A

In [36]:
df_3 ['Gender'] = df_3['Gender'].map({
    'Male':10,
    'Female':20
})
df_3.head()

   Index Animals  Gender Homly Types
0      1     Cat      10   Yes     A
1      2     Dog      10   Yes     B
2      3   Mouse      10   Yes     C
3      4   Mouse      10   Yes     C
4      5     Dog      20   Yes     A

# Ordinal Encoding

In [37]:
df_4.head()

   Index Animals  Gender Homly Types
0      1     Cat    Male   Yes     A
1      2     Dog    Male   Yes     B
2      3   Mouse    Male   Yes     C
3      4   Mouse    Male   Yes     C
4      5     Dog  Female   Yes     A

In [38]:
from sklearn.preprocessing import OrdinalEncoder

In [39]:
od_enc = OrdinalEncoder()

In [40]:
df_4['Types']  = od_enc.fit_transform(df_4[['Types']])
df_4.head()

   Index Animals  Gender Homly  Types
0      1     Cat    Male   Yes    0.0
1      2     Dog    Male   Yes    1.0
2      3   Mouse    Male   Yes    2.0
3      4   Mouse    Male   Yes    2.0
4      5     Dog  Female   Yes    0.0